### ISSUE TITLE
rozen runpy

### ISSUE THREAD

**Issue by crack00r** [jpetzke/AutoGPT-Instagram#3]
2023-05-05 10:37:43,705 - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2023-05-05 10:37:48,967 - ERROR - Request returns 400 error!
2023-05-05 10:37:48,967 - INFO - Instagram's error message: challenge_required
2023-05-05 10:37:48,968 - INFO - Error type: checkpoint_challenge_required
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Manuel\Desktop\GPT\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\Desktop\GPT\Auto-GPT\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "C:\Users\Manuel\Desktop\GPT\Auto-GPT\autogpt\main.py", line 118, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Manuel\Desktop\GPT\Auto-GPT\autogpt\plugins.py", line 230, in scan_plugins
    loaded_plugins.append(a_module())
                          ^^^^^^^^^^
  File "C:\Users\Manuel\AppData\Roaming\Python\Python311\site-packages\abstract_singleton\__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\AutoGPT-Instagram-master.zip\AutoGPT-Instagram-master\src\auto_gpt_instagram\__init__.py", line 36, in __init__
TypeError: can only concatenate str (not "NoneType") to str
Drücken Sie eine beliebige Taste . . .

**Comment by jpetzke** [comment]
The program seems to have failed to log in to Instagram and received a "challenge_required" error message, indicating that Instagram has detected suspicious activity and requires the user to complete a verification challenge before logging in.

I suggest you log in manually on your browser, as this may fix this problem.
