### ISSUE TITLE
KeyError: 'ds_user'

### ISSUE THREAD

**Issue by dje3392** [jpetzke/AutoGPT-Instagram#4]
WARNING: Plugin AutoGPT_Instagram found. But not in the allowlist... Load? (y/n): y
2023-05-06 20:54:52,214 - INFO - Instabot version: 0.117.0 Started
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 118, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
  File "/app/autogpt/plugins.py", line 230, in scan_plugins
    loaded_plugins.append(a_module())
  File "/usr/local/lib/python3.10/site-packages/abstract_singleton/__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
  File "plugins/auto_gpt_instagram.zip/auto_gpt_instagram/__init__.py", line 32, in __init__
  File "plugins/auto_gpt_instagram.zip/auto_gpt_instagram/instagram.py", line 14, in login_instagram
  File "/usr/local/lib/python3.10/site-packages/instabot/bot/bot.py", line 443, in login
    if self.api.login(**args) is False:
  File "/usr/local/lib/python3.10/site-packages/instabot/api/api.py", line 240, in login
    self.load_uuid_and_cookie(load_cookie=use_cookie, load_uuid=use_uuid)
  File "/usr/local/lib/python3.10/site-packages/instabot/api/api.py", line 199, in load_uuid_and_cookie
    return load_uuid_and_cookie(self, load_uuid=load_uuid, load_cookie=load_cookie)
  File "/usr/local/lib/python3.10/site-packages/instabot/api/api_login.py", line 352, in load_uuid_and_cookie
    cookie_username = self.cookie_dict["ds_user"]
**KeyError: 'ds_user'**

I've double checked my account and I am able to login via instagram

**Comment by didier15774** [comment]
hola buenas tardes, felicitaciones por el complemento, si logro que funcione seria muy bueno que AutoGPT pueda hacer publicaciones automaticamente en instagram.
tengo 2 consulta, si son tan amables de responderme.
1 - Agregue el nombre de  AutoGPT_Instagram al archivo .env pero me sigue diciendo que no esta permitido, ya no deberia decirme que no esta permitido, verdad?

2- Mis credenciales de instagram estan bien y las ingrese en el archivo .env pero igual da error al intentar conectarse
         WARNING: Plugin AutoGPT_Instagram found. But not in the allowlist... Load? (y/n): y
        2023-05-06 19:56:24,474 - INFO - Instabot version: 0.117.0 Started
        2023-05-06 19:56:24,474 - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
        2023-05-06 19:56:29,318 - ERROR - Request returns 400 error!
        2023-05-06 19:56:29,318 - INFO - Instagram's error message: challenge_required
        2023-05-06 19:56:29,318 - INFO - Error type: checkpoint_challenge_required
        Failed to log in to Instagram as xxxxxxxxxxx

Como puedo solucionar estos incidentes?

archivo .env
################################################################################
### PLUGINS
INSTAGRAM_USERNAME=XXXXXXXXXXX
INSTAGRAM_PASSWORD=XXXXXXXXXXX
################################################################################

ALLOWLISTED_PLUGINS=AutoGPT-Instagram,

**Comment by jpetzke** [comment]
@didier15774 

1. Preste atención a la ortografía correcta AutoGPT_Instagram al ingresar el complemento en la lista de permitidos. Actualmente utiliza el guión (-) en lugar del guión bajo (_).
2. El mensaje de error indica que necesita resolver un captcha para iniciar sesión en Instagram. Para resolver esto, inicie sesión en Instagram manualmente una vez.

**Comment by didier15774** [comment]
Gracias Jpetzke por la respuesta. ahora ya no me esta pidiendo que confirme al complemento y con tus consejos no da error al inicio de secion, pero si da unos errores despues de un rato de estar trabajando.

estos son los errores, alguien sabe que puede ser??

PLAN:
-  Use 'google' command to search for Instagram accounts related to software development services.
CRITICISM:  I need to ensure that the Instagram accounts I find are relevant to the software development services and will provide valuable insights on Instagram marketing strategies.
NEXT ACTION:  COMMAND = google ARGUMENTS = {'query': 'software development services instagram accounts'}
SYSTEM:  Command google returned: [ { "title": "Top 10 Instagram Accounts to Improve Your Coding Abilities", "href": "https://www.thetrainingroom.com/blog/it-and-development/october-2021/top-10-instagram-accounts-to-improve-your-coding-a", "body": "Web Dev Official has a huge following on Instagram and offers daily advice and insight on key areas within front and backend development. It reveals the coding languages and databases used by big companies like Netflix and Twitch as well as guides to Linux, React and various CSS systems." }, { "title": "8 Web Developers Worth Following on Instagram - BrainStation▒", "href": "https://brainstation.io/blog/8-web-developers-worth-following-on-instagram", "body": "Thankfully, Instagram is home to Programmers and Developers sharing ideas and inspirational posts in an easy-to-digest way. To help you connect with other Developers and stay in the loop about what's going on in the world of web development, we put together a list of Instagram accounts worth following. Morgan.codes" }, { "title": "Top 100 Programming Influencers in 2023 - Feedspot Blog", "href": "https://blog.feedspot.com/programming_instagram_influencers/", "body": "Bio Web Developer --- Logging error ---
Traceback (most recent call last):
  File "D:\Fulanito\Agente\autogpt\logs.py", line 197, in emit
    print(word, end="", flush=True)
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4bb' in position 0: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Fulanito\Agente\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\Fulanito\Agente\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "D:\Fulanito\Agente\autogpt\main.py", line 186, in run_auto_gpt
    agent.start_interaction_loop()
  File "D:\Fulanito\Agente\autogpt\agent\agent.py", line 283, in start_interaction_loop
    logger.typewriter_log("SYSTEM: ", Fore.YELLOW, result)
  File "D:\Fulanito\Agente\autogpt\logs.py", line 102, in typewriter_log
    self.typing_logger.log(
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1559, in log
    self._log(level, msg, args, **kwargs)
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1634, in _log
    self.handle(record)
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 978, in handle
    self.emit(record)
  File "D:\Fulanito\Agente\autogpt\logs.py", line 207, in emit
    self.handleError(record)
Message: 'Command google returned: [\n    {\n        "title": "Top 10 Instagram Accounts to Improve Your Coding Abilities",\n        "href": "https://www.thetrainingroom.com/blog/it-and-development/october-2021/top-10-instagram-accounts-to-improve-your-coding-a",\n        "body": "Web Dev Official has a huge following on Instagram and offers daily advice and insight on key areas within front and backend development. It reveals the coding languages and databases used by big companies like Netflix and Twitch as well as guides to Linux, React and various CSS systems."\n    },\n    {\n        "title": "8 Web Developers Worth Following on Instagram - BrainStation▒",\n        "href": "https://brainstation.io/blog/8-web-developers-worth-following-on-instagram",\n        "body": "Thankfully, Instagram is home to Programmers and Developers sharing ideas and inspirational posts in an easy-to-digest way. To help you connect with other Developers and stay in the loop about what\'s going on in the world of web development, we put together a list of Instagram accounts worth following. Morgan.codes"\n    },\n    {\n        "title": "Top 100 Programming Influencers in 2023 - Feedspot Blog",\n        "href": "https://blog.feedspot.com/programming_instagram_influencers/",\n        "body": "Bio Web Developer \U0001f4bb Freelance Full-Stack Web Developer & Web Designer \U0001f4cd \U0001f1f3\U0001f1f1 based ** One and ONLY account ** milly@millyberst.com \U0001f447 Check out my portfolio Instagram Handle @millywebdeveloper Instagram Followers 32,400 Website https://www.millyberst.com Location Almelo, Nederland 24. Morgan"\n    },\n    {\n        "title": "Hire the best Instagram API developers - Upwork",\n        "href": "https://www.upwork.com/hire/instagram-api-developers/",\n        "body": "Hire Freelancers Talk to a Recruiter. Clients rate Instagram API developers. 4.6/5. based on 280 client reviews. Development & IT Talent. Full Stack Developers. (Current) Instagram API Developers. $30/hr."\n    },\n    {\n        "title": "Instagram APIs | Facebook for Developers",\n        "href": "https://developers.facebook.com/products/instagram/apis/",\n        "body": "Instagram APIs lets you manage and build unique services. Gain tools to help your business interact with the Instagram community. ... Instagram professionals - owners of Instagram Business and Creator accounts. Get Started. Learn More: Read Case Studies. Start Building: Read Docs. Instagram Basic Display API."\n    },\n    {\n        "title": "Web Developer | Coding Beast (@coding.beast) - Instagram",\n        "href": "https://www.instagram.com/coding.beast/",\n        "body": "81K Followers, 233 Following, 363 Posts - See Instagram photos and videos from Web Developer | Coding Beast (@coding.beast)"\n    },\n    {\n        "title": "20 Best Instagram Growth Services (Updated For 2023) - Kicksta",\n        "href": "https://blog.kicksta.co/best-instagram-growth-service/",\n        "body": "20 Best Instagram Growth Services 1. Kicksta Kickstahelps you get real, organic followers by automating engagement marketing tactics. After you create an account, you provide Kicksta with a few sample accounts whose followers are people you want to target."\n    },\n    {\n        "title": "The Rise of Cyber Models and AI Accounts on Instagram",\n        "href": "https://medium.datadriveninvestor.com/the-rise-of-cyber-models-and-ai-accounts-on-instagram-82c096a8fce1",\n        "body": "Ultimately there are still many questions unanswered about CGI models and especially influencers floating around Instagram. Because this is a fairly new development in society it\'s hard to gauge whether the rise of AI Instagram accounts is a positive step for the future or a negative one. Written by Delfina Forstmann. Related Articles On BOLDFISH"\n    }\n]'
Arguments: ()
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Fulanito\Agente\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Fulanito\Agente\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "D:\Fulanito\Agente\autogpt\main.py", line 186, in run_auto_gpt
    agent.start_interaction_loop()
  File "D:\Fulanito\Agente\autogpt\agent\agent.py", line 112, in start_interaction_loop
    assistant_reply = chat_with_ai(
                      ^^^^^^^^^^^^^
  File "D:\Fulanito\Agente\autogpt\llm\chat.py", line 165, in chat_with_ai
    agent.summary_memory = update_running_summary(
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Fulanito\Agente\autogpt\memory_management\summary_memory.py", line 78, in update_running_summary
    content_dict = json.loads(event["content"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Toro\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 13 column 9 (char 1065)
Press any key to continue...

Saludos y gracias

**Comment by jpetzke** [comment]
esto se parece más a un error con AutoGPT.  Recomendaría buscar una solución allí.
